/* ============================================================================
   THE HOME-SCREEN ICONS, GENERATED — not pasted in as four opaque binaries.

   A PWA needs PNGs on disk: the browser's install machinery reads them from
   the manifest, and it will not run our code to get them. So they are static
   files in `public/`. But an icon nobody can regenerate is an icon whose
   colours drift away from the app the first time the theme moves, and this
   repository's rule is that a colour has ONE home (`src/theme.js`).

   So the files are generated by this script, from the theme, and committed.
   Run it again after any change to the palette:

       node scripts/make-icons.mjs

   DEV-ONLY, AND IT ADDS NO DEPENDENCY. A PNG is a signature, three chunks and
   a CRC, and the only compression it needs is `zlib`, which node already has.
   Pulling in an image library to draw four rectangles and a line would put a
   package in the tree for something the standard library does.

   WHAT IT DRAWS. The app's own visual language, reduced until it survives at
   192px: a payoff line over a zero line, GREEN where the trade makes money and
   RED where it loses. Not a logo — the picture the whole app is built on.
============================================================================ */

import { deflateSync } from "node:zlib";
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { PALETTES } from "../src/theme.js";

const OUT = join(dirname(fileURLToPath(import.meta.url)), "..", "public");

/* ---- the colours, from the one place they live ---------------------------
   The DARK palette: an icon sits on somebody's wallpaper, not on our page, and
   a dark tile reads on both a light and a dark home screen. */
const P = PALETTES.dark;
const hex = (h) => {
  const c = h.replace("#", "");
  return [0, 2, 4].map((i) => parseInt(c.slice(i, i + 2), 16));
};
const BG = hex(P.bg), GREEN = hex(P.green), RED = hex(P.red), ZERO = hex(P.dim);

/* ---- PNG: signature, IHDR, IDAT, IEND ----------------------------------- */

const CRC_TABLE = (() => {
  const t = new Int32Array(256);
  for (let n = 0; n < 256; n++) {
    let c = n;
    for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
    t[n] = c;
  }
  return t;
})();
const crc32 = (buf) => {
  let c = -1;
  for (let i = 0; i < buf.length; i++) c = CRC_TABLE[(c ^ buf[i]) & 0xff] ^ (c >>> 8);
  return (c ^ -1) >>> 0;
};
const chunk = (type, data) => {
  const len = Buffer.alloc(4); len.writeUInt32BE(data.length);
  const body = Buffer.concat([Buffer.from(type, "ascii"), data]);
  const crc = Buffer.alloc(4); crc.writeUInt32BE(crc32(body));
  return Buffer.concat([len, body, crc]);
};

/** An RGB pixel buffer (no alpha: these tiles are opaque by design) to a PNG. */
function png(rgb, size) {
  const ihdr = Buffer.alloc(13);
  ihdr.writeUInt32BE(size, 0); ihdr.writeUInt32BE(size, 4);
  ihdr[8] = 8;    // bit depth
  ihdr[9] = 2;    // colour type 2 = truecolour RGB
  // 10, 11, 12 stay 0: deflate, adaptive filtering, no interlace.
  // Each scanline carries a leading filter byte. 0 = none: these are flat
  // blocks of colour, so a filter would buy almost nothing and cost clarity.
  const raw = Buffer.alloc(size * (size * 3 + 1));
  for (let y = 0; y < size; y++) {
    raw[y * (size * 3 + 1)] = 0;
    rgb.copy(raw, y * (size * 3 + 1) + 1, y * size * 3, (y + 1) * size * 3);
  }
  return Buffer.concat([
    Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]),
    chunk("IHDR", ihdr),
    chunk("IDAT", deflateSync(raw, { level: 9 })),
    chunk("IEND", Buffer.alloc(0)),
  ]);
}

/* ---- the picture --------------------------------------------------------
   THE PAYOFF OF A BULL CALL SPREAD, which is the structure this app proposes
   more than any other: flat and losing below the lower strike, rising between
   the strikes, flat and winning above the upper one.

   `payoff(x)` returns a value in [-1, 1] where 0 is the break-even line, so
   the sign decides the colour exactly as `payoffBands()` does on screen. */
const LOSS = -0.62, GAIN = 0.78, KNEE_LO = 0.26, KNEE_HI = 0.68;
const payoff = (x) => {
  if (x <= KNEE_LO) return LOSS;
  if (x >= KNEE_HI) return GAIN;
  return LOSS + ((x - KNEE_LO) / (KNEE_HI - KNEE_LO)) * (GAIN - LOSS);
};

/**
 * Draw one icon.
 *
 * `inset` is the share of the tile kept clear on every side. A MASKABLE icon is
 * cropped by the platform to whatever shape it likes — a circle on one phone, a
 * squircle on another — and only the middle ~80% is guaranteed to survive. So
 * the maskable tile draws the same picture smaller, inside a wider margin,
 * rather than being a different picture.
 *
 * Drawn at 4x and averaged down: the diagonal is the whole mark, and a diagonal
 * drawn at 1x on a 192px tile is a staircase.
 */
function draw(size, inset) {
  const SS = 4, N = size * SS;
  const acc = new Float64Array(size * size * 3);
  const left = N * inset, right = N * (1 - inset);
  const span = right - left;
  const midY = N / 2, halfH = (N * (1 - 2 * inset)) / 2;
  const lineW = N * 0.085, zeroW = N * 0.016;

  // Distance from a point to the payoff polyline, in supersampled pixels.
  const pts = [[0, LOSS], [KNEE_LO, LOSS], [KNEE_HI, GAIN], [1, GAIN]]
    .map(([x, y]) => [left + x * span, midY - y * halfH]);
  const segDist = (px, py, [ax, ay], [bx, by]) => {
    const dx = bx - ax, dy = by - ay;
    const t = Math.max(0, Math.min(1, ((px - ax) * dx + (py - ay) * dy) / (dx * dx + dy * dy || 1)));
    return Math.hypot(px - (ax + t * dx), py - (ay + t * dy));
  };

  for (let y = 0; y < N; y++) {
    for (let x = 0; x < N; x++) {
      let col = BG;
      // The zero line first, so the payoff is drawn OVER it: the line is the
      // subject and the axis is the context.
      if (x >= left && x <= right && Math.abs(y - midY) <= zeroW / 2) col = ZERO;
      let near = Infinity;
      for (let i = 0; i < pts.length - 1; i++) near = Math.min(near, segDist(x, y, pts[i], pts[i + 1]));
      if (near <= lineW / 2) {
        // THE SIGN DECIDES THE COLOUR, read from the payoff at this x — not
        // from which side of the line the pixel is on. Same rule as the bands.
        const xs = Math.max(0, Math.min(1, (x - left) / span));
        col = payoff(xs) >= 0 ? GREEN : RED;
      }
      const o = (Math.floor(y / SS) * size + Math.floor(x / SS)) * 3;
      acc[o] += col[0]; acc[o + 1] += col[1]; acc[o + 2] += col[2];
    }
  }
  const out = Buffer.alloc(size * size * 3);
  for (let i = 0; i < out.length; i++) out[i] = Math.round(acc[i] / (SS * SS));
  return png(out, size);
}

/* ---- the four files -----------------------------------------------------
   192 and 512 are what the manifest specification asks every installable app
   for. The 512 MASKABLE is the one Android actually puts on the home screen
   when it is offered one, and its wider inset is the safe zone. The 180 is
   Safari's: iOS reads `apple-touch-icon` from the page, not the manifest. */
const FILES = [
  ["icon-192.png", 192, 0.16],
  ["icon-512.png", 512, 0.16],
  ["icon-512-maskable.png", 512, 0.26],
  ["apple-touch-icon-180.png", 180, 0.16],
];

for (const [name, size, inset] of FILES) {
  const buf = draw(size, inset);
  writeFileSync(join(OUT, name), buf);
  console.log(`  ${name.padEnd(26)} ${String(size).padStart(3)}px  ${String(buf.length).padStart(6)} bytes`);
}
console.log("\nColours read from src/theme.js (the dark palette). Re-run after any palette change.");
